CREATE TABLE IF NOT EXISTS user_assessments (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  assessment_id INTEGER REFERENCES assessments(id) ON DELETE CASCADE,
  has_access BOOLEAN DEFAULT TRUE,
  purchased_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE user_assessments
ADD COLUMN IF NOT EXISTS attempts_used INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_attempts INTEGER DEFAULT 3;

ALTER TABLE user_assessments ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;